repos:
    - repo: local
      hooks:
          - id: black
            name: black
            language: system
            entry: python3 -m black
            types: [python]
            exclude: 'front/'
          - id: flake8
            name: flake8
            language: system
            entry: flake8
            types: [python]
            exclude: 'front/'
          - id: jslint
            name: jslint
            language: system
            entry: yarn lint
            types: [vue, javascript]
            exclude: 'api/'